### PR TITLE
docs(README): update with homebrew install option

### PR DESCRIPTION
**Pull request by adam-moss**
Signed-off-by: Adam Moss <2951486+adam-moss@users.noreply.github.com>

### CODE REVIEW

**Review by DavidAnson — CHANGES_REQUESTED** [review]
Looks good, thank you! Could you please change the base branch to "next" instead of "main"? (You can do this in the web UI for GitHub, without rebase, etc..)

**Comment by adam-moss** [comment]
> Looks good, thank you! Could you please change the base branch to "next" instead of "main"? (You can do this in the web UI for GitHub, without rebase, etc..)

All done :)

**Comment by adam-moss** [comment]
Oh, my fork branch has ran you CI and failed to push the docker container, might need to block that 👍

**Review by DavidAnson — APPROVED** [review]
Thanks!

**Pull request merged**
