### PR TITLE
add fix command to pre-commit-hooks

### PR DESCRIPTION
**Pull request by Cielquan**

### CODE REVIEW

**Comment by DavidAnson** [comment]
pre-commit is meant for identifying issues before code review: https://pre-commit.com/

But markdownlint-cli2-fix will make changes to files that are part of that review as well as
files that are not. Those changes will not be included with the review unless they are committed. But I don't think that will happen?

So I am not sure it makes sense to offer fix with pre-commit. Can you explain how this would be used, please?

**Comment by Cielquan** [comment]
I use pre-commit for linting as well for formatting for some time now. First I run all the formatters and then the linters, so the linters don't complain about things the formatters will fix.

I am not the only one doing this. This is indeed a pattern I see quite often. Even in the [repos of the pre-commit](https://github.com/orgs/pre-commit/repositories) you can find a mirror of `prettier` and `isort` which both format code.

[pre-commit.ci](https://pre-commit.ci/) (also made by anthony) allows you to not only run you pre-commit hooks for pull requests but also commit changes made by formatters back to the pull request.

So I see no problem in adding the fix command.

**Comment by DavidAnson** [comment]
Ok, could you please update the PR for "next" branch (see CONTRIBUTING.md) and add a third entry for the new markdownlint-cli2-config command?

**Comment by Cielquan** [comment]
Sure will do.

**Comment by nschonni** [comment]
https://github.com/igorshubovych/markdownlint-cli/blob/master/.pre-commit-hooks.yaml has a separate "fix" target, because it is invoked differently with a CLI flag. In CLI2, the fix flag is part of the config file, so I don't think a separate target makes sense

**Comment by DavidAnson** [comment]
Fixed by your commit in #37.

**Pull request closed without merging**
