### PR TITLE
Improve codequality readme

### PR DESCRIPTION
**Pull request by mschoettle**
With fixing #98 the use of the Docker image is simplified.

This PR improves the codequality formatter README to reflect that.

### CODE REVIEW

**Comment by mschoettle** [comment]
May you please publish the updated version on the npm registry? :-)

**Comment by DavidAnson** [comment]
According to npm, I did so 20 minutes ago. :)

**Comment by DavidAnson** [comment]
Oh, you mean the formatters?

**Comment by DavidAnson** [comment]
Done, please check again. Sorry for the oversight! FYI, I think the version in the Docker container image will already be the right one based on how that's created - but if you find otherwise, please let me know.

**Comment by mschoettle** [comment]
Thanks! I thought it was released automatically but makes sense it is not.

**Pull request merged**
