### PR TITLE
Bump yaml from 2.2.1 to 2.2.2

### PR DESCRIPTION
**Pull request by viceice**
- https://github.com/advisories/GHSA-f9xv-q969-pqx4

### CODE REVIEW

**Comment by DavidAnson** [comment]
Already done: https://github.com/DavidAnson/markdownlint-cli2/blob/b48513fabeb0bd83222b4c8657c3940e1fde2b9c/package.json#L69

**Comment by viceice** [comment]
but not on main and not released yet in v0.7.0?

**Comment by DavidAnson** [comment]
Correct.

**Comment by viceice** [comment]
can you please do a release with the fixed `yaml` package to resolve the security issue?

**Comment by viceice** [comment]
I'm not sure how urgent. what's the worst case when that happens inside the cli?

**Comment by DavidAnson** [comment]
Exceptions from YAML are already handled. I think this is pretty minor, but because npm is calling it out at install time, I will patch the library and CLI2 soon.

**Comment by viceice** [comment]
thank you 🤗

**Comment by DavidAnson** [comment]
Fixed in v0.7.1

**Comment by viceice** [comment]
thank you 🤗

**Pull request closed without merging**
