### PR TITLE
Clarify specification of file in markdownlint-cli2-config

### PR DESCRIPTION
**Pull request by andrewnicols**
I wasted an hour trying to work out why this was not working with my supplied configuration file.

Can I suggest that the configuration file in use be specified as part of the output, and where a configuration was specified and not available or not valid that an error be raised.

### CODE REVIEW

**Comment by DavidAnson** [comment]
I think the problem here was that the code today assumes the file name will have a certain structure (which is slightly more flexible than what you document) and ignores it otherwise. That's my error, sorry for your trouble! I will update the code to produce an appropriate error if the specified config file is not recognized or usable. Once done, I think the issue you had would have been clear and easily corrected.

**Review by DavidAnson — CHANGES_REQUESTED** [review]
I will address this issue differently and am leaving this comment to prevent myself from merging this PR. No action is needed on your part. Details here: https://github.com/DavidAnson/markdownlint-cli2/pull/46#issuecomment-1120636842

**Comment by andrewnicols** [comment]
Thanks David,

Yes I agree that it makes sense as to the reason. The lack of error messages just led me on a wild goose chase.

Similarly, I've just spent another chunk of time trying to work out why my configuration was not working per the docs, and it was because I'd accidentally named it `.markdownlint.cjs` instead of `.markdownlint-cli2.cjs`.

Perhaps a log message could indicate the file that was read, and whether it was parsed using markdownlint/markdownlint-cli format, or markdownlint-cli2 format since they differ in a subtle yet important difference.

**Comment by DavidAnson** [comment]
Each directory can have its own differently-named configuration file. I'm wary of cluttering the output with all that info by default. However, I'm wondering about adding a diagnostic mode to help with scenarios like this.

**Comment by DavidAnson** [comment]
With my commit above, this scenario will emit an error.

**Pull request closed without merging**
