### PR TITLE
Add --no-banner option hiding CLI version output

### PR DESCRIPTION
**Pull request by nikolaik**
When using the pre-commit hook and passing multiple files, the output becomes harder to read than necessary when then banner is displayed for each file processed.

Example of existing output
```console
❯ pre-commit run -a
markdownlint-cli2........................................................Failed
- hook id: markdownlint-cli2
- exit code: 1

markdownlint-cli2 v0.12.1 (markdownlint v0.33.0)
markdownlint-cli2 v0.12.1 (markdownlint v0.33.0)
markdownlint-cli2 v0.12.1 (markdownlint v0.33.0)
doc1.md:1 MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading [Context: "Not a title"]
doc2.md:127 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
markdownlint-cli2 v0.12.1 (markdownlint v0.33.0)
doc3:35 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
```

To limit the noise when running the hook we also run with:
```json
{
  "noProgress": true,
  "showFound": false
}
```

Output with this PR, passing the `--no-banner` option:
```console
❯ pre-commit run -a
markdownlint-cli2........................................................Failed
- hook id: markdownlint-cli2
- exit code: 1

doc3.md:1 MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading [Context: "Not a title"]
doc3.md:127 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
doc4:35 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
```

Would it make sense to make this the new default behaviour?

### CODE REVIEW

**Comment by DavidAnson** [comment]
This project has a strong preference for configuration file settings over command line parameters (except where necessary), so were we to move forward with this, I would want to see it as a setting instead.

FYI, you do not need to set showFound (above) when noProgress is true.

But my main question is why your pre-commit hook is invoking this tool multiple times instead of passing it a single list of files. That is the common behavior and results in just a single banner.

FYI, the banner is very useful for troubleshooting because it makes clear what version of CLI2 and markdownlint are being used and people are sometimes unsure or unclear about that.

**Comment by nikolaik** [comment]
Thank you for taking the time to review and answers in such detail!

> This project has a strong preference for configuration file settings over command line parameters (except where necessary), so were we to move forward with this, I would want to see it as a setting instead.

I started out with adding it as a configuration option, but then I saw that the logging happened before the config parsing was finished. Would you prefer if I changed it to a config option `noBanner` and moved the banner logging after config parsing is done then? 
 
> FYI, you do not need to set showFound (above) when noProgress is true.

Ah! I'll remove that from the test setup

> But my main question is why your pre-commit hook is invoking this tool multiple times instead of passing it a single list of files. That is the common behavior and results in just a single banner.

I'm not sure why, though it happens consistently when running with `pre-commit run -a` at least. I'll double check if I'm using the hook or pre-commit wrong.

> FYI, the banner is very useful for troubleshooting because it makes clear what version of CLI2 and markdownlint are being used and people are sometimes unsure or unclear about that.

I see your point about accurate error reporting and I opted to make the option default false to not change existing behaviour. I would argue that it's hurting the UX for regular CLI users though.

**Comment by DavidAnson** [comment]
I am OK with the idea of adding this as a configuration parameter, but I have some specific thoughts about how to do it. Since I just published a new version of the library, CLI2 is my current project and I can make this change if you don’t want or won’t be able to do so in the next few days.

My thinking is to make the banner string a file-level constant and move the logMessage of it down to the first opportunity after getBaseOptions (as you point out). A new “noBanner“ property should be supported to suppress the banner at that time. I think that will work for most cases, but not when an exception comes out of readOptionsOrConfig or getBaseOptions. To handle that, I think a try/finally will be needed to wrap that small section of the code (lines 940-959) and output the banner in the finally. If the base configuration failed to load, output the banner anyway. I don’t like that this scoping breaks a couple of constant variables, but I don’t see a cleaner way from reading the code on my phone right now. The showHelp method should display the banner unconditionally.

With these changes, all existing test cases should pass unaltered and only the new test cases for this setting should be needed.

Let me know what you think.

**Comment by nikolaik** [comment]
Thank you for taking the time <3 The approach you are describing sounds good. I don't have much time to work on this, so if you have a plan, go for it!

**Pull request closed without merging**
