### PR TITLE
chore: setup Dependabot for version updates

### PR DESCRIPTION
**Pull request by nschonni**
Add Dependabot for the core package.json, GitHub Actions, and sub-packages with dependencies

### CODE REVIEW

**Comment by nschonni** [comment]
I believe this needs to be on `main` rather than `next` to work correctly, or do you want me to make it target PRs to the `next` as well?

**Comment by nschonni** [comment]
changed it so the PRs will go to the `next` branch, but I think this config needs to land on `main` to take affect

**Comment by DavidAnson** [comment]
Thanks. This is handy, but I don't like how it litters the commit timeline with "noise". Also, it doesn't seem to handle breaking change updates well (issuing the same broken PR every week).

**Comment by nschonni** [comment]
You can tell it to ignore a version full for things like the breaking ESM change in `chalk` with `@dependabot ignore this major version` so it stops PRs for that major version.
For now I set it as weekly, but you could up it to monthly if you find it's too noisy

**Comment by DavidAnson** [comment]
Do you know if there's a way to tell it to do updates all together? I don't mind once a week if it's one commit each week that updates everything that's eligible. I looked at their documentation and didn't see anything about this. I realize that will make it harder to tell what broke if the tests fail, but I'm fine with that. Either give up or use that opportunity to send a separate commit for each individual update.

**Comment by nschonni** [comment]
No, I think the PRs are atomic, but I have seen custom things like https://github.com/streetsidesoftware/cspell/blob/main/.github/workflows/update-dependencies.yml if you want to roll your own

**Comment by DavidAnson** [comment]
It looks like I'm not the only person who wants grouping behavior from Dependabot: https://github.com/dependabot/dependabot-core/issues/1190

There are some existing actions that support that, but I don't love the idea of giving them access to the GitHub token: https://github.com/marketplace/actions/update-node-dependencies

This CLI looks like it would automate the manual steps I go through before a release and I might start using it (through Docker): https://www.npmjs.com/package/npm-check-updates

**Comment by DavidAnson** [comment]
Per the discussion above, I've added an npm script to make package upgrade easier: https://github.com/DavidAnson/markdownlint-cli2/commit/b44527ef52a054e6cc608ba6c31d0df3bc59ddae

(Related, something that's complicating matters nowadays is dependent packages updating to use ESM. I (currently) think libraries should stay on Common JS for the sake of their consumers. I may upgrade this project to ESM, but haven't decided yet.)

**Comment by nschonni** [comment]
OK, FYI, you can use a `.ncurc*` config to "reject" those ESM packages https://github.com/raineorshine/npm-check-updates#configuration-files, that is still a manual listing you'd need to do

**Comment by DavidAnson** [comment]
Good to know, thanks! I played around with it a little just now and the situation is a bit of a mess, I think. Gradually upgrading a project doesn't seem especially well supported. For now, I like the subtle reminders to do this eventually. :)

**Pull request closed without merging**
